algoritmo "exercício"
// Função :   Faça um programa que mostre a soma e a média de todos os números pares entre 1 e 500.
// Autor :  Ana Vicentine
// Data : 23/08/2022
// Seção de Declarações 
var
contador, numero, soma, qtde:inteiro
media:real

inicio
// Seção de Comandos
para contador de 1 ate 500 faca
     se (contador mod 2=0) entao
     soma <- soma + contador
     fimse
fimpara
escreval ("A soma é: ",soma)
media <- soma/250
escreval ("A média é: ",media)
fimalgoritmo
