algoritmo "trocar valores"
// Função : trocar valores de duas váriaveis
// Autor :  ana laura
// Data : 08/03/2022
// Seção de Declarações 
var
 a,b,c:inteiro
inicio
// Seção de Comandos 
a <- 10
b <- 20
escreval("valor da váriavel a ==>",a)
escreval("valor da váriavel b ==>",b)
escreval ("****************************")
c <- a
a <- b
b <- c
escreval("resultado da troca de valores")
escreval("valor da váriavel a ==>",a)
escreval("valor da váriavel b ==>",b)
fimalgoritmo
