algoritmo "Impares_100200"
// Função : Escrever um algoritmo que gera e escreve os números ímpares entre 100 e 200.
// Autor : Ana Vicentine
// Data : 20/09/2022
// Seção de Declarações 
var
contador: inteiro

inicio
// Seção de Comandos 

contador <- 100
 enquanto contador < 200 faca
 se contador mod 2 = 1 entao
 escreval(contador)
 fimse
 contador <- contador + 1
 fimenquanto
fimalgoritmo
