algoritmo "REVISÃO3"
// Função : Revisão
// Autor : Ana Vicentine
// Data : 20/09/2022
// Seção de Declarações 
var
quadrado: inteiro
contador, contador2: inteiro

inicio
// Seção de Comandos
escreval ("Qual o tamanho do quadrado: ")
leia (quadrado)
para contador de 1 ate quadrado faca
   para contador2 de 1 ate quadrado faca
      escreva ("*")
   fimpara
   escreval ()
fimpara






fimalgoritmo
