algoritmo "REVISÃO2"
// Função : REVISÃO
// Autor : Ana Vicentine
// Data : 20/09/2022
// Seção de Declarações 
var
idade,contador,quantidade:inteiro

inicio
// Seção de Comandos
para contador de 1 ate 10 faca
        escreval ("Digite a idade: ")
        leia (idade)
        se idade >= 18 entao
           quantidade <- quantidade + 1
        fimse
fimpara
escreval ("No total ",quantidade," pessoas tem 18 anos ou mais")





fimalgoritmo
