algoritmo "EXEMPLO"
// Função :  solicite um número inteiro e que faça uma operação
// Autor :  Ana Vicentine
// Data : 06/09/2022
// Seção de Declarações 
var
numero,contador: inteiro
resultado: real
inicio
// Seção de Comandos
escreval ("Digite um número: ")
leia (numero)
para contador de 1 ate numero faca
    resultado <- resultado + (1/contador)
fimpara

escreval ("Resultado é =>",resultado)

fimalgoritmo
