algoritmo "EXERCÍCIO 1"
// Função : exibir a tabuada de um número inteiro
// Autor :  Ana Vicentine
// Data : 30/08/2022
// Seção de Declarações 
var
contador, numero:inteiro
inicio
// Seção de Comandos 
escreval ("Digite um número: ")
leia (numero)
escreval ("                             ")
para contador de 1 ate 10 faca
     escreval(numero," x ",contador," = ", numero*contador)
fimpara
fimalgoritmo
